export const STATIC_GALLERY_URLS = {
  thumbnails: {
    minecraft: {
      'T1.jpg': 'https://i.postimg.cc/SN7cp2pW/T1.jpg',
      'T2.jpg': 'https://i.postimg.cc/Nf7Rw9w8/T2.jpg',
      'T3.jpg': 'https://i.postimg.cc/ncYqtjt4/T3.jpg',
      'T4.jpg': 'https://i.postimg.cc/FHr3Fr9c/T4.jpg',
      'T5.jpg': 'https://i.postimg.cc/K8GBcGZB/T5.jpg',
      'T6.jpg': 'https://i.postimg.cc/W1NgpN2G/T6.jpg',
      'T7.jpg': 'https://i.postimg.cc/RZSKCSMT/T7.jpg',
      'T8.jpg': 'https://i.postimg.cc/sgj7fjVn/T8.jpg',
      'T9.jpg': 'https://i.postimg.cc/x1fMjffD/T9.jpg',
      'T10.jpg': 'https://i.postimg.cc/x1fMjf0W/T10.jpg',
      'T11.jpg': 'https://i.postimg.cc/GmLG3LcW/T11.jpg',
      'T13.jpg': 'https://i.postimg.cc/y8L9kMdQ/T13.jpg',
      'T14.jpg': 'https://i.postimg.cc/CxcDz35S/T14.jpg',
      'T15.jpg': 'https://i.postimg.cc/2S0vVsyz/T15.jpg',
      'T16.jpg': 'https://i.postimg.cc/y8L9kMxd/T16.jpg',
      'T17.jpg': 'https://i.postimg.cc/L8xfnc5s/T17.jpg',
      'T18.jpg': 'https://i.postimg.cc/YSjFgdL2/T18.jpg',
      'T19.jpg': 'https://i.postimg.cc/LshPfxgs/T19.jpg',
      'T20.jpg': 'https://i.postimg.cc/MGXBR9fn/T20.jpg',
    },
    roblox: {
      'T1.jpg': 'https://i.postimg.cc/Kjh36Fqr/T1.jpg',
      'T2.jpg': 'https://i.postimg.cc/GtnTWr7P/T2.jpg',
      'T3.jpg': 'https://i.postimg.cc/sxCGky64/T3.jpg',
      'T4.jpg': 'https://i.postimg.cc/D0349Fjc/T4.jpg',
      'T5.jpg': 'https://i.postimg.cc/T1v5zG74/T5.jpg',
      'T6.jpg': 'https://i.postimg.cc/Rh1J98yp/T6.jpg',
      'T7.jpg': 'https://i.postimg.cc/Hn08HKRR/T7.jpg',
      'T8.jpg': 'https://i.postimg.cc/ZnPvZg2g/T8.jpg',
      'T9.jpg': 'https://i.postimg.cc/br0S8MWK/T9.jpg',
      'T10.png': 'https://i.postimg.cc/ZY6drBny/T10.png',
      'T11.jpg': 'https://i.postimg.cc/MZ1QyMH0/T11.jpg',
      'T12.jpg': 'https://i.postimg.cc/Wp0kMFzM/T12.jpg',
    },
  },
  keyarts: {
    minecraft: {
      'Key1.jpg': 'https://i.postimg.cc/d14gXtt6/Key1.jpg',
      'Key2.jpg': 'https://i.postimg.cc/TwCBSYY9/Key2.jpg',
      'Key3.jpg': 'https://i.postimg.cc/xCtB7TT3/Key3.jpg',
    },
    roblox: {},
  },
  promocional: {
    minecraft: {
      'Promo1.jpg': 'https://i.postimg.cc/nVS6GzWQ/Promo1.jpg',
      'Promo2.jpg': 'https://i.postimg.cc/66bDf3P2/Promo2.jpg',
      'Promo3.jpg': 'https://i.postimg.cc/wx4SQvrt/Promo3.jpg',
      'Promo4.jpg': 'https://i.postimg.cc/y6pwydG3/Promo4.jpg',
      'Promo5.jpg': 'https://i.postimg.cc/PfVBQx7W/Promo5.jpg',
      'Promo6.jpg': 'https://i.postimg.cc/qBD9xRFx/Promo6.jpg',
      'Promo7.jpg': 'https://i.postimg.cc/jq3G451Q/Promo7.jpg',
      'Promo8.jpg': 'https://i.postimg.cc/3JyzShMG/Promo8.jpg',
      'Promo9.jpg': 'https://i.postimg.cc/jdWBgTVP/Promo9.jpg',
      'Promo10.jpg': 'https://i.postimg.cc/WbDxWVR0/Promo10.jpg',
      'Promo11.jpg': 'https://i.postimg.cc/NfyZJth4/Promo11.jpg',
      'Promo12.jpg': 'https://i.postimg.cc/7YCjs48k/Promo12.jpg',
      'Promo13.jpg': 'https://i.postimg.cc/9F4s8252/Promo13.jpg',
    },
    roblox: {},
  },
  profiles: {
    minecraft: {
      'profile1.jpg': 'https://i.postimg.cc/tgzcZCPj/profile1.jpg',
      'Profile2.jpg': 'https://i.postimg.cc/mrSnz2MR/Profile2.jpg',
      'profile3.jpg': 'https://i.postimg.cc/pdBShX8v/profile3.jpg',
    },
    roblox: {},
  },
}

export const STATIC_DECORATION_URLS = {
  'outros/decoracoes/roblox.png': 'https://i.postimg.cc/bNN1pYYB/roblox.png',
  'outros/decoracoes/sentado.png': 'https://i.postimg.cc/fTTYDWW1/sentado.png',
  'outros/decoracoes/Perfil_About.png': 'https://i.postimg.cc/zGwN7NKz/Perfil_About.png',
  'outros/decoracoes/Etapa1.png': 'https://i.postimg.cc/tCCFpRRh/Etapa1.png',
  'outros/decoracoes/Etapa2.png': 'https://i.postimg.cc/xTTLnjjv/Etapa2.png',
  'outros/decoracoes/Etapa3.png': 'https://i.postimg.cc/Prr1Tffz/Etapa3.png',
  'outros/decoracoes/grande.png': 'https://i.postimg.cc/655Ct66V/grande.png',
  'outros/antesedepois/antes.jpg': 'https://i.postimg.cc/KzPtvRMy/antes.jpg',
  'outros/antesedepois/depois.jpg': 'https://i.postimg.cc/85RLPj6Q/depois.jpg',
  'outros/antesedepois/pintura.png': 'https://i.postimg.cc/XJf97pCM/pintura.png',
  'banner/Banner.png': 'https://i.postimg.cc/q7QmBDVj/Banner.png',
}
